version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: postgres
      POSTGRES_DB: storefront_dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5000:5432"